spring:
  application:
    name: BharatVa-Auth
  datasource:
    url: jdbc:mysql://localhost:3306/bharat_va_auth?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    time-zone: UTC
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USER}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jwt:
    secret: ${JWT_SECRET_KEY}